replicaCount: 2

image:
  repository: cicd-so-happy.maxwin.com.tw:5000/racev-strapi
  tag: "1.18.0"
  pullPolicy: IfNotPresent

labels:
  app.maxwin/component: backend
  app.maxwin/name: racev-strapi

service:
  type: ClusterIP
  port: 1337 # service port

persistence:
  # /public/uploads 資料夾
  uploads:
    enabled: false # 關掉的話就不會建立 pvc，只產生一個暫存的空資料夾來儲存
    storageClass: ""
    size: 100Mi
  # strapi build 資料夾快取 (Init Container 使用)
  buildCache:
    enabled: false # 開啟後會啟用 Init Container 機制，讓 build 結果可跨 Pod 重啟快取
    storageClass: ""
    size: 2Gi

# 可以放一些 strapi 啟動前要先掛載的設定檔，key 是檔名，value 是檔案內容
configHooks: {}

# apiJsConfig: |-
#   module.exports = {
#     rest: {
#       defaultLimit: 300,
#       maxLimit: 300,
#       withCount: true,
#     },
#   };

config:
  # for strapi
  TZ: Asia/Taipei
  DATABASE_HOST: mysql
  DATABASE_PORT: 3306
  PUBLIC_URL: http://localhost:1337
  # for oidc
  STRAPI_ADMIN_OIDC_ENABLED: false
  STRAPI_ADMIN_OIDC_ISSUER: KEYCLOAK-OIDC
  OIDC_REDIRECT_URI: http://localhost:1337/strapi-plugin-sso/oidc/callback
  OIDC_CLIENT_ID: my-oidc-client
  OIDC_AUTHORIZATION_ENDPOINT: https://my.keycloak.host/auth/realms/myrealms/protocol/openid-connect/auth
  OIDC_TOKEN_ENDPOINT: https://my.keycloak.host/auth/realms/myrealms/protocol/openid-connect/token
  OIDC_USER_INFO_ENDPOINT: https://my.keycloak.host/auth/realms/myrealms/protocol/openid-connect/userinfo

secret:
  # for strapi
  APP_KEYS: strapi-key
  API_TOKEN_SALT: strapi-token-salt
  ADMIN_JWT_SECRET: strapi-jwt-secret
  JWT_SECRET: jwt-secret
  DATABASE_NAME: my-strapi-db
  DATABASE_USERNAME: strapi
  DATABASE_PASSWORD: change-me
  # for oidc
  OIDC_CLIENT_SECRET: my-oidc-client-secret

# 專門給 Init Container 用的(用於 npm run build)
initResources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi # Webpack 很吃記憶體，上限給高一點防 OOM

# 給 Main Container 用的
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

probes:
  startup:
    initialDelaySeconds: 60 # 先等 60 秒再開始探測
    periodSeconds: 10 # 每 10 秒探測一次
    failureThreshold: 12 # 10s * 12 = 最多給 120 秒 (2 分鐘) Build
  liveness:
    initialDelaySeconds: 0 # 有 startup 確認服務已啟動，這裡改成 0 即可
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3
