apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner

commonLabels:
  app.kubernetes.io/name: nfs-provisioner

helmCharts:
  - name: nfs-server-provisioner
    repo: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
    version: 1.8.0
    releaseName: nfs-provisioner
    namespace: nfs-provisioner
    valuesFile: values.yaml

patches:
  - target:
      kind: "*"
    patch: |
      metadata:
        namespace: nfs-provisioner
