apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmi-daily-report
spec:
  timeZone: "Asia/Taipei"
  schedule: "0 8 * * *" # default: UTC, set timeZone for local time
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 300 # 5 mins
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hmi-daily-report
              image: cicd-so-happy.maxwin.com.tw:5000/hmi-daily-reporter:1.0.0
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: hmi-daily-report-cm
                - secretRef:
                    name: hmi-daily-report-secret
              resources:
                requests:
                  cpu: 128m
                  memory: 256Mi
                limits:
                  cpu: 256m
                  memory: 512Mi
          restartPolicy: Never
