apiVersion: v1
data:
  DB_DATABASE: RAC_Bus
  DB_PORT: "1438"
  DB_SERVER: 10.40.1.105
  DRY_RUN: "false"
  TZ: Asia/Taipei
kind: ConfigMap
metadata:
  labels:
    app.maxwin/component: backend
    app.maxwin/name: qisda-vehicle-data-porter
  name: qisda-vehicle-data-porter-cm
  namespace: apts-racev
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.maxwin/component: backend
    app.maxwin/name: qisda-vehicle-data-porter
  name: qisda-vehicle-data-porter
  namespace: apts-racev
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app.maxwin/component: backend
        app.maxwin/name: qisda-vehicle-data-porter
    spec:
      activeDeadlineSeconds: 90
      template:
        metadata:
          labels:
            app.maxwin/component: backend
            app.maxwin/name: qisda-vehicle-data-porter
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: qisda-vehicle-data-porter-cm
            - secretRef:
                name: qisda-vehicle-data-porter-secret
            image: cicd-so-happy.maxwin.com.tw:5000/qisda-vehicle-data-porter:1.0.0
            imagePullPolicy: IfNotPresent
            name: qisda-vehicle-data-porter
            resources:
              limits:
                cpu: 256m
                memory: 512Mi
              requests:
                cpu: 128m
                memory: 256Mi
          restartPolicy: OnFailure
  schedule: '* * * * *'
  startingDeadlineSeconds: 50
