{{- range .Values.targets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ .name | kebabcase }}-secret
  namespace: {{ $.Release.Namespace }}
  {{- with $.Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- $globalSecret := $.Values.secret | default dict }}
  {{- $localSecret := .extraSecret | default dict }}
  {{- $mergedSecret := merge (deepCopy $localSecret) $globalSecret }}
  {{- range $key, $value := $mergedSecret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
