apiVersion: batch/v1
kind: CronJob
metadata:
  name: vehicle-alert-processor
spec:
  #schedule: "0 * * * *" # every hour
  schedule: "*/5 * * * *" # every 10 minutes
  startingDeadlineSeconds: 1800 # 30 mins
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: vehicle-alert-processor
              envFrom:
                - configMapRef:
                    name: vehicle-alert-processor-cm
                - secretRef:
                    name: vehicle-alert-processor-secret
              # env:
              #   - name: PYTHONUNBUFFERED
              #     value: "1"
              resources:
                requests:
                  cpu: 256m
                  memory: 512Mi
                limits:
                  cpu: 512m
                  memory: 1Gi
                # requests:
                #   cpu: 500m
                #   memory: 512Mi
                # limits:
                #   cpu: 1000m
                #   memory: 2Gi
