apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../bases"

configMapGenerator:
  - name: vehicle-alert-processor-cm
    behavior: merge
    envs:
      - ".env"

secretGenerator:
  - name: vehicle-alert-processor-secret
    behavior: merge
    literals:
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Pass123

generatorOptions:
  disableNameSuffixHash: true

namespace: apts-racev

commonLabels:
  app.maxwin/name: vehicle-alert-processor
  app.maxwin/component: backend

images:
  - name: cicd-so-happy.maxwin.com.tw:5000/vehicle-alert-processor
    newTag: 1.0.0

patches:
  - path: cronjob.yaml
