apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../bases"

configMapGenerator:
  - name: vehicle-charge-checkout-cm
    behavior: merge
    envs:
      - ".env"
  - name: vehicle-charge-checkout-target-cm
    literals:
      - TARGET_DATE=2025-08-04T01:00:04.688Z
      - TARGET_DATE_RANGE=-29h
      # - RANGE_OFFSET=5h

secretGenerator:
  - name: vehicle-charge-checkout-secret
    behavior: merge
    literals:
      # docker
      - STRAPI_API_TOKEN=506d25b2e0502d0720ce220a1d1e9ef9447cefdf0a193c8e50a9d57e2438cb5b0cda964bdb139c36320b6bedddf358804262365b4b94764879eaa3f92e699bf06773cc230daf8a684bac208a3a46c7500e1ab71fc012654d79e6bf9469d7d4cbb2009d3b0fcb126096c079337e899ec0e752acf73280f92a8a085235b21c4277

generatorOptions:
  disableNameSuffixHash: true

namespace: apts-racev

commonLabels:
  app.maxwin/name: vehicle-charge-checkout
  app.maxwin/component: backend

images:
  - name: cicd-so-happy.maxwin.com.tw:5000/vehicle-charge-checkout
    newTag: 1.2.2

patches:
  - path: cronjob.yaml
