{{- range .Values.jobs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{- range $key, $value := $.Values.commonLabels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
type: Opaque
data:
  # 合併基礎敏感設定與 extraSecret，並自動進行 Base64 編碼
  {{- $merged := merge $.Values.commonSecret (default dict .extraSecret) }}
  {{- range $key, $value := $merged }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}
