apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    version: 18.2.1
    releaseName: keycloak
    namespace: keycloak
    valuesFile: values.yaml
