apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apts-racev

resources:
  - ../bases

configMapGenerator:
  - name: afrersales-discord-bot-cm
    behavior: merge
    envs:
      - .env

images:
  - name: cicd-so-happy.maxwin.com.tw:5000/afrersales-discord-bot
    newTag: 1.0.0

labels:
  - pairs:
      app.maxwin/name: afrersales-discord-bot
      app.maxwin/component: backend
    includeSelectors: true
    includeTemplates: true

patches:
  - path: patch-deploy.yaml
