{{- range .Values.stations }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: charger-edcp-sender-target-cm-{{ .code }}{{- if .suffix }}-{{ .suffix }}{{- end }}
data:
  TARGET_STATION_CODES: "{{ .code }}"
{{- $merged := merge $.Values.commonConfig (default dict .extraConfig) }}
{{- range $key, $value := $merged }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{- end }}
