# image 為 charger-edcp-sender 使用的 image 版本與拉取策略
image:
  repository: cicd-so-happy.maxwin.com.tw:5000/charger-edcp-sender
  pullPolicy: IfNotPresent
  tag: "1.6.11"

# commonConfig 為 charger-edcp-sender 需要的基礎環境變數
commonConfig:
  DEBUG: "*,-nodemon*,-logStore*,-ioredis*"
  DRY_RUN: true
  EXACT_INDEX: true
  PARALLEL_ENABLED: false
  ELASTIC_API: http://host.docker.internal:9200
  STRAPI_CHARGER_STATION_API: http://host.docker.internal:1337/api/charger-stations
  STRAPI_EDCP_CHARGE_LOG_API: http://host.docker.internal:1337/api/edcp-charge-logs
  REDIS_SERVER: 10.40.201.11:6380

# secret 為 charger-edcp-sender 需要的環境變數中較為隱私需放入 secret 的部分
secret:
  STRAPI_API_TOKEN: "my strapi token"

# stations: 需要產生的 cronjob 的 station 清單
# 各 station 會分別產生一個 cornjob
# code: station code
# schedule: cron 表達式(排程時間)
# suffix: cronjob name 添加的後綴(因 10-1 需做兩次，故加入後綴)
# extraConfig: 針對不同 station 的 cronjob 的環境變數，會覆寫與 commonConfig 重複的環境變數，若無重複則基於 commonConfig 增加
stations:
  - code: 9-1
    schedule: "35 14 * * *"
    extraConfig:
      TARGET_DATE_RANGE: -32h
  - code: 10-1
    suffix: "morning"
    schedule: "36 14 * * *"
    extraConfig:
      TARGET_DATE_RANGE: -32h
  - code: 10-1
    suffix: "afternoon"
    schedule: "37 14 * * *"
    extraConfig:
      TARGET_DATE_RANGE: -32h
