apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts
helmCharts:
  - name: daily-error-report
    releaseName: daily-error-report
    valuesFile: values.yaml
    namespace: apts-racev
