# image 為 daily-error-report 使用的映像檔版本與拉取策略
image:
  repository: cicd-so-happy.maxwin.com.tw:5000/daily-error-report
  pullPolicy: IfNotPresent
  tag: "1.0.0"

# commonLabels
commonLabels:
  app.maxwin/component: backend
  app.maxwin/name: daily-error-report

# commonConfig 為大部分排程需要共用的預設變數 (在此預設以 13 資料庫為 common)
commonConfig:
  TZ: "Asia/Taipei"
  DRY_RUN: "true"
  SMTP_SERVER: "192.168.160.125"
  SENDER_EMAIL: "report@racev.com"
  DB_SERVER: "192.168.192.13"
  DB_NAME: "RAC_Bus"
  DB_USER: "rac_dvp"

# commonSecret 為大部分排程共用的敏感資料
commonSecret:
  DB_PASSWORD: "db password"

# jobs: 各任務各自的 CronJob、時間與覆寫之變數
jobs:
  - name: anomaly-report
    schedule: "0 8 * * *"
    jobType: "ANOMALY_REPORT"
    # Anomaly 使用 140 資料庫與特定收件人
    extraConfig:
      DB_SERVER: "192.168.186.140"
      DB_USER: "rac_dev"
      RECEIVER_EMAIL: "EBUS-Status-Reporting-Group@racev.com"
    extraSecret:
      DB_PASSWORD: "anomaly_password"

  - name: send-200-data
    schedule: "0 8 * * *"
    jobType: "SEND_200_DATA"
    extraConfig:
      RECEIVER_EMAIL: "default-200-receiver@racev.com"

  - name: send-qisda-version
    schedule: "0 9 * * 1"
    jobType: "SEND_QISDA_VERSION"
    extraConfig:
      RECEIVER_EMAIL: "default-qisda-receiver@racev.com"
