apiVersion: apps/v1
kind: Deployment
metadata:
  name: aftersales-discord-bot
spec:
  replicas: 1
  selector: {}
  template:
    spec:
      containers:
        - name: aftersales-discord-bot
          image: cicd-so-happy.maxwin.com.tw:5000/aftersales-discord-bot:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "128m"
          envFrom:
            - configMapRef:
                name: aftersales-discord-bot-cm
            - secretRef:
                name: aftersales-discord-bot-secret
