apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml

configMapGenerator:
  - name: afrersales-discord-bot-cm
    envs:
      - .env.example

secretGenerator:
  - name: afrersales-discord-bot-secret
    envs:
      - secret.env.example

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.maxwin/name: afrersales-discord-bot
      app.maxwin/component: backend
    includeSelectors: true
    includeTemplates: true
