apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ems

commonLabels:
  app.maxwin/name: charger-edcp-sender
  app.maxwin/component: backend

helmGlobals:
  chartHome: ../charts
helmCharts:
  - name: cronjobs-chart
    valuesFile: values.yaml