apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts
helmCharts:
  - name: cronjobs-chart
    namespace: ems
    releaseName: charger-edcp-sender
    valuesFile: values.yaml
