apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.17.10
      resources:
        requests:
          cpu: "0.5"
          memory: "128Mi"
        limits:
          cpu: "1"
          memory: "250Mi"
      ports:
        - containerPort: 80
