apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret
  namespace: {{ $.Release.Namespace }}
  labels:
{{- range $key, $value := $.Values.commonLabels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
