apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts

helmCharts:
  - name: qisda-vehicle-data-porter
    releaseName: qisda-vehicle-data-porter
    valuesFile: values.yaml
    namespace: apts-racev
