apiVersion: v2
name: charger-edcp-sender-scheduler
description: Helm chart for create charger-edcp-sender Cronjobs

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# chart 版本
version: 0.1.0

# 應用程式版本
appVersion: "1.6.11"
