apiVersion: batch/v1
kind: CronJob
metadata:
  name: gps-offline-reporter
spec:
  # schedule: "0 3 * * *" # default: UTC, set timeZone for local time
  schedule: "30 13 * * *" # default: UTC, set timeZone for local time
  startingDeadlineSeconds: 21600 # 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gps-offline-reporter
              envFrom:
                - configMapRef:
                    name: gps-offline-reporter-cm
              resources:
                requests:
                  cpu: 128m
                  memory: 256Mi
                limits:
                  cpu: 256m
                  memory: 512Mi
